---
title: "writing_functions"
output: html_document
date: "2023-10-26"
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

```

## Set seed for reproducibility 
```{r}
set.seed(12345)
```

### Z score function

Z scores subtract the mean and divide the sd. 
```{r}
x_vec = rnorm(20, mean = 5, sd = .3)
```
 
Compute Z score for 'x_vec'
```{r}
(x_vec - mean (x_vec)) / sd(x_vec)
```

Write a function to do this! 
```{r}
z_score = function (x) {
  
  if(!is.numeric(x)) {
    stop("Argument should be numbers")
  } else if(length(x) < 2) {
    stop("You need at least 2 arguments to get z score")
  }
  
  z = (x- mean(x)) / sd(x)
  
  z
  
}
```

Check that it works. 
```{r}
z_score(x = x_vec)
```

Keep checking 
```{r, error = TRUE}
z_score(x = 3)

z_score(c("my", "name", "is", "grace"))

z_score(c(TRUE, TRUE, FALSE, TRUE))

z_score(iris)
```

